// Generated by CoffeeScript 1.7.1
(function() {
  window.helloWorld = function() {
    return "Hello world!";
  };

  window.disemvowel = function(str) {
    return str.replace(/a|e|i|o|u/gi, "");
  };

}).call(this);
