// Generated by CoffeeScript 1.7.1
(function() {
  describe("Hello world", function() {
    return it("say world", function() {
      return (expect(helloWorld())).toContain("world");
    });
  });

  describe("Hello world", function() {
    return it("say world", function() {
      return (expect(helloWorld())).toEqual("Hello world!");
    });
  });

  describe("Disemvoweler", function() {
    it("should remove all lowercase vowels", function() {
      return (expect(disemvowel("Hello world"))).toEqual("Hll wrld");
    });
    it("should remove all uppercase vowels", function() {
      return (expect(disemvowel("Artistic Eagle"))).toEqual("rtstc gl");
    });
    it("shouldn't change empty strings", function() {
      return (expect(disemvowel(""))).toEqual("");
    });
    return it("shouldn't change strings with no vowels", function() {
      return (expect("Mhmm")).toEqual("Mhmm");
    });
  });

}).call(this);
